name = "themajorinsight-worker"
main = "src/worker/index.ts"
compatibility_date = "2026-09-07"
workers_dev = true

[vars]
APP_NAME = "The Major Insight"

[[d1_databases]]
binding = "DB"
database_name = "themajorinsight"
database_id = "e49a5931-a942-49c6-a51c-bd632112b1eb"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "themajorinsight-media"
