"use client";
import { useMemo,useState } from "react";
type Asset=Record<string,any>; type Post={id:string;title:string};
const empty={alt_text:"",caption:"",creator:"",original_source_url:"",license:"",attribution:"",associated_post:""};
export function MediaLibrary({initialAssets,posts,canDelete}:{initialAssets:Asset[];posts:Post[];canDelete:boolean}){
 const [assets,setAssets]=useState(initialAssets),[query,setQuery]=useState(""),[type,setType]=useState(""),[file,setFile]=useState<File|null>(null),[meta,setMeta]=useState(empty),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const shown=useMemo(()=>assets.filter(a=>(!type||a.mime_type===type)&&`${a.filename} ${a.alt_text} ${a.creator} ${a.license}`.toLowerCase().includes(query.toLowerCase())),[assets,query,type]);
 const update=(k:string,v:string)=>setMeta(x=>({...x,[k]:v}));
 async function upload(){if(!file||!meta.alt_text.trim())return setMessage("Choose an image and provide alt text.");setBusy(true);setMessage("");try{const p=await json(await fetch("/api/admin/media/presign",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({filename:file.name,mimeType:file.type,size:file.size})}));const put=await fetch(p.url,{method:"PUT",headers:p.headers,body:file});if(!put.ok)throw new Error("R2 upload failed. Check bucket CORS settings.");const dimensions=await imageDimensions(file);const saved=await json(await fetch("/api/admin/media",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...meta,...dimensions,object_key:p.key,r2_url:p.publicUrl,filename:file.name,mime_type:file.type,file_size:file.size})}));setAssets(x=>[saved,...x]);setFile(null);setMeta(empty);setMessage("Upload complete.")}catch(e){setMessage(e instanceof Error?e.message:"Upload failed.")}finally{setBusy(false)}}
 async function save(a:Asset){setBusy(true);try{await json(await fetch("/api/admin/media",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(a)}));setMessage("Metadata saved.")}catch(e){setMessage(e instanceof Error?e.message:"Save failed.")}finally{setBusy(false)}}
 async function remove(a:Asset){if(!confirm(`Permanently delete ${a.filename} from R2?`))return;setBusy(true);try{await json(await fetch(`/api/admin/media?id=${encodeURIComponent(a.id)}`,{method:"DELETE"}));setAssets(x=>x.filter(v=>v.id!==a.id));setMessage("Asset deleted.")}catch(e){setMessage(e instanceof Error?e.message:"Delete failed.")}finally{setBusy(false)}}
 return <><section className="admin-panel media-upload"><h2>Upload to Cloudflare R2</h2><p className="admin-note">Upload only images you own or are licensed to publish. This library never scrapes or republishes third-party images automatically.</p><div className="media-fields"><label>Image (JPG, PNG, WebP, AVIF; max 15 MB)<input type="file" accept=".jpg,.jpeg,.png,.webp,.avif,image/jpeg,image/png,image/webp,image/avif" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><Fields value={meta} set={update} posts={posts}/></div><button className="admin-primary" disabled={busy||!file||!meta.alt_text.trim()} onClick={upload}>{busy?"Working…":"Upload image"}</button>{message&&<p role="status" className="media-message">{message}</p>}</section><div className="media-controls"><input type="search" placeholder="Search filename, alt text, creator, license…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={type} onChange={e=>setType(e.target.value)}><option value="">All formats</option>{["image/jpeg","image/png","image/webp","image/avif"].map(x=><option key={x}>{x}</option>)}</select></div><div className="media-grid">{shown.map(a=><article className="media-card" key={a.id}><img src={a.r2_url} alt={a.alt_text||""} loading="lazy" width={a.width} height={a.height}/><div><strong>{a.filename}</strong><small>{a.width}×{a.height} · {formatBytes(a.file_size)} · {a.mime_type}</small><Fields value={a} posts={posts} set={(k,v)=>setAssets(xs=>xs.map(x=>x.id===a.id?{...x,[k]:v}:x))}/><div className="media-actions"><button onClick={()=>navigator.clipboard.writeText(a.r2_url)}>Copy CDN URL</button><button disabled={busy||!a.alt_text?.trim()} onClick={()=>save(a)}>Save</button>{canDelete&&<button className="danger" disabled={busy} onClick={()=>remove(a)}>Delete</button>}</div></div></article>)}</div>{!shown.length&&<p className="admin-empty">No media matches these filters.</p>}</>}
function Fields({value,set,posts}:{value:Asset;set:(k:string,v:string)=>void;posts:Post[]}){return <div className="media-metadata"><label>Alt text *<input value={value.alt_text||""} onChange={e=>set("alt_text",e.target.value)} required/></label><label>Caption<input value={value.caption||""} onChange={e=>set("caption",e.target.value)}/></label><label>Photographer / creator<input value={value.creator||""} onChange={e=>set("creator",e.target.value)}/></label><label>Original source URL<input type="url" value={value.original_source_url||""} onChange={e=>set("original_source_url",e.target.value)}/></label><label>License<input value={value.license||""} onChange={e=>set("license",e.target.value)}/></label><label>Attribution<input value={value.attribution||""} onChange={e=>set("attribution",e.target.value)}/></label><label>Associated post<select value={value.associated_post||""} onChange={e=>set("associated_post",e.target.value)}><option value="">None</option>{posts.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label></div>}
async function json(r:Response){const body=await r.json();if(!r.ok)throw new Error(body.error||"Request failed.");return body}function formatBytes(x:number){return x>1048576?`${(x/1048576).toFixed(1)} MB`:`${Math.ceil(x/1024)} KB`}function imageDimensions(file:File){return new Promise<{width:number;height:number}>((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{resolve({width:img.naturalWidth,height:img.naturalHeight});URL.revokeObjectURL(url)};img.onerror=()=>{reject(new Error("The selected file is not a valid image."));URL.revokeObjectURL(url)};img.src=url})}
