"use client";

import Link from "next/link";
import { useActionState, useEffect, useRef, useState } from "react";
import { savePost } from "@/app/admin/(protected)/posts/actions";
import { editorialWarnings, makeSlug } from "@/lib/editorial";

type Option={id:string;name:string}; type Source={label:string;url:string;publisher:string};
export type EditorPost = Record<string, any> & { id?:string; content?:{html?:string}; post_tags?:{tag_id:string}[]; post_sources?:Source[] };
export function PostEditor({post={},authors,categories,tags,revisions=[],audit=[],canApprove}:{post?:EditorPost;authors:Option[];categories:Option[];tags:Option[];revisions?:Record<string,any>[];audit?:Record<string,any>[];canApprove:boolean}) {
  const [state, action, pending]=useActionState(savePost,{}); const formRef=useRef<HTMLFormElement>(null); const editorRef=useRef<HTMLDivElement>(null);
  const [title,setTitle]=useState(post.title || ""), [slug,setSlug]=useState(post.slug || ""), [slugTouched,setSlugTouched]=useState(!!post.id);
  const [html,setHtml]=useState(post.content?.html || "<p></p>"), [sources,setSources]=useState<Source[]>(post.post_sources || []), [dirty,setDirty]=useState(false);
  const [author,setAuthor]=useState(post.author_id || ""), [image,setImage]=useState(post.featured_image_url || ""), [alt,setAlt]=useState(post.featured_image_alt || ""), [seo,setSeo]=useState(post.seo_description || ""), [scheduled,setScheduled]=useState(toLocal(post.scheduled_at));
  const warnings=editorialWarnings({title,slug,authorId:author,bodyHtml:html,featuredImageUrl:image,featuredImageAlt:alt,seoDescription:seo,sources,scheduledAt:scheduled});
  useEffect(()=>{ if(!post.id) return; const timer=setInterval(()=>{ if(dirty && !pending) formRef.current?.requestSubmit(formRef.current.querySelector<HTMLButtonElement>("[data-autosave]")); },45000); return()=>clearInterval(timer); },[dirty,pending,post.id]);
  useEffect(()=>{ if(state.ok) setDirty(false); },[state]);
  function format(command:string,value?:string){ editorRef.current?.focus(); document.execCommand(command,false,value); sync(); }
  function sync(){ const value=editorRef.current?.innerHTML || ""; setHtml(value); setDirty(true); }
  function insert(kind:"link"|"image"|"table"|"callout") { if(kind==="link"){const url=prompt("Link URL (https://…)");if(url)format("createLink",url);} if(kind==="image"){const url=prompt("Image URL (https://…)");if(url)format("insertHTML",`<img src="${safe(url)}" alt="">`);} if(kind==="table")format("insertHTML","<table><tbody><tr><th>Heading</th><th>Heading</th></tr><tr><td>Cell</td><td>Cell</td></tr></tbody></table><p></p>"); if(kind==="callout")format("insertHTML",'<aside data-callout="true"><p><strong>Key point</strong></p><p>Add context here.</p></aside><p></p>'); }
  return <form ref={formRef} action={action} className="editor-form" onChange={()=>setDirty(true)}>
    <input type="hidden" name="id" value={post.id || ""}/><input type="hidden" name="body_html" value={html}/><input type="hidden" name="sources_json" value={JSON.stringify(sources)}/>
    <header className="editor-commandbar"><div><span className="save-state">{pending?"Saving…":dirty?"Unsaved changes":state.savedAt?`Saved ${new Date(state.savedAt).toLocaleTimeString()}`:"Ready"}</span>{post.id&&<Link href={`/admin/posts/${post.id}/preview`} target="_blank">Preview ↗</Link>}</div><div>
      <button className="admin-secondary" name="intent" value="draft">Save draft</button><button className="admin-secondary" name="intent" value="review">Submit for review</button>{canApprove&&<><button className="admin-secondary" name="intent" value="schedule">Schedule</button><button className="admin-primary" name="intent" value="publish">Publish</button></>}<button hidden data-autosave name="intent" value="draft">Autosave</button>
    </div></header>
    {state.error&&<p className="admin-error" role="alert">{state.error}</p>}
    <div className="editor-layout"><div className="editor-main">
      <section className="admin-panel editor-story"><label>Headline<input name="title" value={title} onChange={e=>{setTitle(e.target.value);if(!slugTouched)setSlug(makeSlug(e.target.value))}} placeholder="A precise, compelling headline" required/></label>
      <label>Slug<div className="slug-input"><span>/</span><input name="slug" value={slug} onChange={e=>{setSlugTouched(true);setSlug(e.target.value)}} required/></div></label>
      <label>Excerpt / deck<textarea name="excerpt" defaultValue={post.excerpt || ""} rows={3} maxLength={320} placeholder="Summarize the insight and its value to the reader."/></label></section>
      <section className="admin-panel"><div className="editor-toolbar" role="toolbar" aria-label="Rich text formatting">
        <button type="button" onClick={()=>format("formatBlock","p")}>Paragraph</button><button type="button" onClick={()=>format("formatBlock","h2")}>H2</button><button type="button" onClick={()=>format("formatBlock","h3")}>H3</button><button type="button" onClick={()=>format("bold")}><b>B</b></button><button type="button" onClick={()=>format("italic")}><i>I</i></button><button type="button" onClick={()=>insert("link")}>Link</button><button type="button" onClick={()=>format("insertUnorderedList")}>Bullets</button><button type="button" onClick={()=>format("insertOrderedList")}>Numbers</button><button type="button" onClick={()=>format("formatBlock","blockquote")}>Quote</button><button type="button" onClick={()=>format("formatBlock","pre")}>Code</button><button type="button" onClick={()=>insert("image")}>Image</button><button type="button" onClick={()=>insert("table")}>Table</button><button type="button" onClick={()=>format("insertHorizontalRule")}>Divider</button><button type="button" onClick={()=>insert("callout")}>Callout</button>
      </div><div ref={editorRef} className="rich-editor" contentEditable suppressContentEditableWarning onInput={sync} dangerouslySetInnerHTML={{__html:html}} data-placeholder="Begin writing…"/></section>
      <SourceEditor sources={sources} setSources={v=>{setSources(v);setDirty(true)}}/>
      <section className="admin-panel"><h2>Search presentation</h2><div className="admin-form"><label>SEO title<input name="seo_title" defaultValue={post.seo_title || ""} maxLength={70}/></label><label>Meta description<textarea name="seo_description" value={seo} onChange={e=>setSeo(e.target.value)} rows={3} maxLength={165}/></label><label>Canonical URL<input name="canonical_url" type="url" defaultValue={post.canonical_url || ""}/></label><label>Focus keyword<input name="focus_keyword" defaultValue={post.focus_keyword || ""}/></label></div><div className="seo-preview"><small>THEMAJORINSIGHT.COM</small><strong>{post.seo_title || title || "Article title"}</strong><p>{seo || "Add a useful meta description to preview the search result."}</p></div></section>
    </div><aside className="editor-sidebar">
      <section className="admin-panel"><h2>Publishing</h2><label>Status<select name="status" defaultValue={post.status || "draft"}><option value="draft">Draft</option><option value="review">In review</option>{canApprove&&<><option value="scheduled">Approved / scheduled</option><option value="published">Published</option><option value="archived">Archived</option></>}</select></label><label>Publish date<input type="datetime-local" name="publish_date" defaultValue={toLocal(post.published_at)}/></label><label>Schedule date<input type="datetime-local" name="scheduled_at" value={scheduled} onChange={e=>setScheduled(e.target.value)}/></label>{canApprove&&post.id&&<div className="danger-actions"><button name="intent" value="unpublish">Unpublish</button><button name="intent" value="archive">Archive</button></div>}</section>
      <section className="admin-panel"><h2>Classification</h2><label>Content type<select name="content_type" defaultValue={post.content_type || "Analysis"}>{["Analysis","News","Explainer","Guide","Review","Comparison","Report","Opinion"].map(x=><option key={x}>{x}</option>)}</select></label><label>Category<select name="category_id" defaultValue={post.category_id || ""}><option value="">Select category</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Author<select name="author_id" value={author} onChange={e=>setAuthor(e.target.value)}><option value="">Select author</option>{authors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Tags<select name="tag_ids" multiple defaultValue={(post.post_tags||[]).map(x=>x.tag_id)}>{tags.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><small>Use Ctrl/Cmd to select multiple.</small></label></section>
      <section className="admin-panel"><h2>Featured image</h2><label>Image URL<input type="url" name="featured_image_url" value={image} onChange={e=>setImage(e.target.value)}/></label>{image&&<img className="editor-image-preview" src={image} alt=""/>}<label>Image alt<input name="featured_image_alt" value={alt} onChange={e=>setAlt(e.target.value)}/></label><label>Caption<textarea name="featured_image_caption" defaultValue={post.featured_image_caption || ""}/></label><label>Source attribution<input name="featured_image_credit" defaultValue={post.featured_image_credit || ""}/></label></section>
      <section className="admin-panel checks"><h2>Editorial checks</h2>{warnings.length?<ul>{warnings.map(x=><li key={x}>⚠ {x}</li>)}</ul>:<p className="check-pass">✓ Ready for editorial approval</p>}<label>Change note<input name="change_note" placeholder="What changed?"/></label><label className="check"><input type="checkbox" name="is_editor_pick" defaultChecked={post.is_editor_pick}/> Editor pick</label><label className="check"><input type="checkbox" name="is_featured" defaultChecked={post.is_featured}/> Featured</label><label className="check"><input type="checkbox" name="include_in_newsletter" defaultChecked={post.include_in_newsletter}/> Include in newsletter</label><p className="human-note">AI-assisted work is never auto-published. A human editor must use the Publish action.</p></section>
      {post.id&&<History title="Revision history" items={revisions} render={x=>`Revision ${x.revision_number} · ${x.change_note || "saved"}`}/>} {post.id&&<History title="Change log" items={audit} render={x=>String(x.action).replace("post.","")}/>} 
    </aside></div>
  </form>;
}
function SourceEditor({sources,setSources}:{sources:Source[];setSources:(x:Source[])=>void}) { return <section className="admin-panel"><div className="section-heading"><div><h2>Source checklist</h2><p>Provide direct, verifiable links for factual claims.</p></div><button type="button" className="admin-secondary" onClick={()=>setSources([...sources,{label:"",url:"",publisher:""}])}>Add source</button></div>{sources.length? sources.map((s,i)=><div className="source-row" key={i}><input aria-label="Source label" placeholder="Source title" value={s.label} onChange={e=>setSources(sources.map((x,n)=>n===i?{...x,label:e.target.value}:x))}/><input aria-label="Source URL" type="url" placeholder="https://" value={s.url} onChange={e=>setSources(sources.map((x,n)=>n===i?{...x,url:e.target.value}:x))}/><input aria-label="Publisher" placeholder="Publisher" value={s.publisher} onChange={e=>setSources(sources.map((x,n)=>n===i?{...x,publisher:e.target.value}:x))}/><button type="button" aria-label="Remove source" onClick={()=>setSources(sources.filter((_,n)=>n!==i))}>×</button></div>):<p className="admin-note">No sources added. At least one valid source is required before review.</p>}</section> }
function History({title,items,render}:{title:string;items:Record<string,any>[];render:(x:Record<string,any>)=>string}){return <section className="admin-panel history"><h2>{title}</h2>{items.length?<ol>{items.map((x,i)=><li key={String(x.id||i)}><strong>{render(x)}</strong><time>{new Date(x.created_at).toLocaleString()}</time></li>)}</ol>:<p>No entries yet.</p>}</section>}
function toLocal(value?:string|null){if(!value)return "";const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)} function safe(x:string){return x.replace(/["<>]/g,"")}
